### ISSUE TITLE
File fd leaked

### ISSUE THREAD

**Issue by xutianyi1999** [monoio-rs/monoio#229]
**Version**
└── monoio v0.2.1
    ├── monoio-macros v0.1.0 (proc-macro)

**Platform**
Linux DESKTOP-2CTP7F6 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
65536

**Description**
文件离开作用域后未被关闭，即使整个Runtime都已经被drop了
![image](https://github.com/bytedance/monoio/assets/31791535/36a713d5-679e-455d-a49f-bd96032525c7)

**Comment by ihciah** [comment]
Thanks for reporting, we will try to reproduce and fix it.

**Comment by hxzhao527** [comment]
> 文件离开作用域后未被关闭

预期之内. 在`File::close`中有说明, 这里不再赘述.  
Work as expected. This is described in `File::close` and will not be repeated here.
https://github.com/bytedance/monoio/blob/46c921f5b4962b395b40659145c5eca345659558/monoio/src/fs/file.rs#L470-L497

> 即使整个Runtime都已经被drop了

预期之外. 上面的例子比较特殊, 虽然file离开作用域后确实有通过`Drop`提交`Close`, 但是由于最外层的future已经退出, 导致没有`submit`的时机. 在 #240 中补齐了这个`submit`.
Not expected. The above example is special in that while `Close` is indeed submitted via `Drop` after the file leaves the scope, but there is no timing for `submit` because the outermost future has already exited. This `submit` is made up in #240.
